Update configuration-with-ocis.md
owncloud/ocis-hello pull request #110
Opened 2021-06-11 08:51 UTC by LukasHirt

Since we're registering the greet endpoint in the proxy, we should also use that in the config for the extension in the UI, right? Feel free to close this if it's a nonsense

2021-06-11 09:19 UTC, refs commented
I think we actually removed the ocis-hello references from the proxy. See https://github.com/owncloud/ocis/commit/771f85ce2bfbe55a25d3c858a2c5c9f861eff719

2021-06-11 09:24 UTC, kulmann requested changes
You're right, since ocis-hello depends on having the settings service available it makes sense that the default routing points to the proxy.
Could you also add to the documentation, that the proxy config also needs the following entry:
```
{
          "endpoint": "/hello.js",
          "backend": "http://localhost:9105"
        }
```

2021-06-11 09:24 UTC, kulmann commented on docs/configuration-with-ocis.md
>              "path": "http://localhost:9105/hello.js",
Please also change the path here to 
```suggestion
            "path": "https://localhost:9200/hello.js",
```

2021-06-11 09:40 UTC, LukasHirt commented
@kulmann Done

2021-06-11 09:40 UTC, LukasHirt commented
> I think we actually removed the ocis-hello references from the proxy

We still mention in the docs of ocis-hello to add it manually to the config of proxy

2021-06-11 09:43 UTC, kulmann approved these changes
Thanks for updating this! :heart:

2021-06-11 12:58 UTC, refs approved these changes

2021-06-14 07:48 UTC, wkloucek commented
@LukasHirt  should be already reflected in #https://github.com/owncloud/ocis-hello/pull/104

2021-06-14 07:51 UTC, LukasHirt commented
> should be already reflected in #104 ?

Ah, right, thank you! I like your approach with omitting the address completely much more :rocket: Closing this in favour of that PR

2021-06-14 07:51 UTC, closed without merging